// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: distributed_storage.proto

// Protobuf Java Version: 3.25.3
package com.example.distributedstorage.proto;

public interface ChunkResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:distributedstorage.ChunkResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool found = 1;</code>
   * @return The found.
   */
  boolean getFound();

  /**
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
