// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: distributed_storage.proto

// Protobuf Java Version: 3.25.3
package com.example.distributedstorage.proto;

public final class DistributedStorageProto {
  private DistributedStorageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributedstorage_Chunk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributedstorage_Chunk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributedstorage_ChunkRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributedstorage_ChunkRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributedstorage_ChunkResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributedstorage_ChunkResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributedstorage_StoreChunkResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributedstorage_StoreChunkResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributedstorage_HealthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributedstorage_HealthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributedstorage_HealthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributedstorage_HealthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributedstorage_DownloadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributedstorage_DownloadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributedstorage_ListFilesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributedstorage_ListFilesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributedstorage_ListFilesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributedstorage_ListFilesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031distributed_storage.proto\022\022distributed" +
      "storage\"=\n\005Chunk\022\021\n\tfile_name\030\001 \001(\t\022\023\n\013c" +
      "hunk_index\030\002 \001(\005\022\014\n\004data\030\003 \001(\014\"6\n\014ChunkR" +
      "equest\022\021\n\tfile_name\030\001 \001(\t\022\023\n\013chunk_index" +
      "\030\002 \001(\005\"=\n\rChunkResponse\022\r\n\005found\030\001 \001(\010\022\014" +
      "\n\004data\030\002 \001(\014\022\017\n\007message\030\003 \001(\t\"6\n\022StoreCh" +
      "unkResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030" +
      "\002 \001(\t\"\017\n\rHealthRequest\"2\n\016HealthResponse" +
      "\022\017\n\007healthy\030\001 \001(\010\022\017\n\007node_id\030\002 \001(\t\"$\n\017Do" +
      "wnloadRequest\022\021\n\tfile_name\030\001 \001(\t\"\022\n\020List" +
      "FilesRequest\"\'\n\021ListFilesResponse\022\022\n\nfil" +
      "e_names\030\001 \003(\t2\200\002\n\013StorageNode\022O\n\nStoreCh" +
      "unk\022\031.distributedstorage.Chunk\032&.distrib" +
      "utedstorage.StoreChunkResponse\022O\n\010GetChu" +
      "nk\022 .distributedstorage.ChunkRequest\032!.d" +
      "istributedstorage.ChunkResponse\022O\n\006Healt" +
      "h\022!.distributedstorage.HealthRequest\032\".d" +
      "istributedstorage.HealthResponse2\212\002\n\013Coo" +
      "rdinator\022O\n\nStoreChunk\022\031.distributedstor" +
      "age.Chunk\032&.distributedstorage.StoreChun" +
      "kResponse\022P\n\014DownloadFile\022#.distributeds" +
      "torage.DownloadRequest\032\031.distributedstor" +
      "age.Chunk0\001\022X\n\tListFiles\022$.distributedst" +
      "orage.ListFilesRequest\032%.distributedstor" +
      "age.ListFilesResponseBA\n$com.example.dis" +
      "tributedstorage.protoB\027DistributedStorag" +
      "eProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_distributedstorage_Chunk_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_distributedstorage_Chunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributedstorage_Chunk_descriptor,
        new java.lang.String[] { "FileName", "ChunkIndex", "Data", });
    internal_static_distributedstorage_ChunkRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_distributedstorage_ChunkRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributedstorage_ChunkRequest_descriptor,
        new java.lang.String[] { "FileName", "ChunkIndex", });
    internal_static_distributedstorage_ChunkResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_distributedstorage_ChunkResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributedstorage_ChunkResponse_descriptor,
        new java.lang.String[] { "Found", "Data", "Message", });
    internal_static_distributedstorage_StoreChunkResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_distributedstorage_StoreChunkResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributedstorage_StoreChunkResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_distributedstorage_HealthRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_distributedstorage_HealthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributedstorage_HealthRequest_descriptor,
        new java.lang.String[] { });
    internal_static_distributedstorage_HealthResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_distributedstorage_HealthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributedstorage_HealthResponse_descriptor,
        new java.lang.String[] { "Healthy", "NodeId", });
    internal_static_distributedstorage_DownloadRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_distributedstorage_DownloadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributedstorage_DownloadRequest_descriptor,
        new java.lang.String[] { "FileName", });
    internal_static_distributedstorage_ListFilesRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_distributedstorage_ListFilesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributedstorage_ListFilesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_distributedstorage_ListFilesResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_distributedstorage_ListFilesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributedstorage_ListFilesResponse_descriptor,
        new java.lang.String[] { "FileNames", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
