// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: distributed_storage.proto

// Protobuf Java Version: 3.25.3
package com.example.distributedstorage.proto;

public interface DownloadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:distributedstorage.DownloadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string file_name = 1;</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string file_name = 1;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();
}
