// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: distributed_storage.proto

// Protobuf Java Version: 3.25.3
package com.example.distributedstorage.proto;

public interface HealthResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:distributedstorage.HealthResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool healthy = 1;</code>
   * @return The healthy.
   */
  boolean getHealthy();

  /**
   * <code>string node_id = 2;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 2;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();
}
