// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: distributed_storage.proto

// Protobuf Java Version: 3.25.3
package com.example.distributedstorage.proto;

public interface ListFilesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:distributedstorage.ListFilesRequest)
    com.google.protobuf.MessageOrBuilder {
}
