// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: distributed_storage.proto

// Protobuf Java Version: 3.25.3
package com.example.distributedstorage.proto;

public interface StoreChunkResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:distributedstorage.StoreChunkResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
